# Generated by Django 3.0.6 on 2020-05-27 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='overview',
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(),
        ),
    ]
