# Generated by Django 3.0.6 on 2020-05-27 11:32

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20200527_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='overview',
            field=ckeditor.fields.RichTextField(default='test'),
            preserve_default=False,
        ),
    ]
